In [75]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [76]:
data1 = pd.read_csv("symptom_to_diagnosis.csv")
data2 = pd.read_csv("Symptom2Disease.csv")

In [77]:
print(data1.columns)
print(data2.columns)

Index(['label', 'input'], dtype='str')
Index(['label', 'input'], dtype='str')

In [78]:
for i in range(len(data1.columns)):
    print(data1.columns[i], ":", data1[data1.columns[i]].nunique())

# data1.rename(columns={'output_text':'label'},inplace=True)
# data1.rename(columns={'input_text':'text'},inplace=True)

label : 22
input : 849

In [79]:
data1

,label,input
0,cervical spondylosis,I've been having a lot of pain in my neck and ...
1,impetigo,I have a rash on my face that is getting worse...
2,urinary tract infection,I have been urinating blood. I sometimes feel ...
3,arthritis,I have been having trouble with my muscles and...
4,dengue,I have been feeling really sick. My body hurts...
...,...,...
848,varicose veins,My veins are bulging and painful. I can't stan...
849,migraine,I have been having headaches for a while now. ...
850,impetigo,I have a rash on my face that is very painful ...
851,allergy,I have a stuffy nose and nasal congestion. I s...
852,pneumonia,I've been feeling really sick lately. I've had...

In [80]:
for i in range(len(data2.columns)):
    print(data2.columns[i], ":", data2[data2.columns[i]].nunique())

label : 24
input : 1153

In [81]:
unique_vals = data1['label'].unique()
len(unique_vals)

22

In [82]:
unique_vals2 = data2['label'].unique()
len(unique_vals2)

24

In [83]:
list1=[]
list2=[]
for i in range(len(unique_vals)):
    for j in range(len(unique_vals2)):
        # print(unique_vals2[j])
        if(unique_vals2[j] == unique_vals[i]):
            list1.append(unique_vals[i]) 
            list2.append(unique_vals2[j])

In [84]:
print(list1)
print(list2)

['urinary tract infection', 'drug reaction', 'allergy', 'gastroesophageal reflux disease', 'diabetes', 'peptic ulcer disease']
['urinary tract infection', 'drug reaction', 'allergy', 'gastroesophageal reflux disease', 'diabetes', 'peptic ulcer disease']

In [85]:
data1['label'] = (
    data1['label']
    .str.lower()
    .str.strip()
    .str.replace(r'\s+', ' ', regex=True)
)

data2['label'] = (
    data2['label']
    .str.lower()
    .str.strip()
    .str.replace(r'\s+', ' ', regex=True)
)

In [86]:
df = pd.concat([data1, data2], axis=0, ignore_index=True)

In [87]:
df

,label,input
0,cervical spondylosis,I've been having a lot of pain in my neck and ...
1,impetigo,I have a rash on my face that is getting worse...
2,urinary tract infection,I have been urinating blood. I sometimes feel ...
3,arthritis,I have been having trouble with my muscles and...
4,dengue,I have been feeling really sick. My body hurts...
...,...,...
2048,diabetes,I'm shaking and trembling all over. I've lost ...
2049,diabetes,"Particularly in the crevices of my skin, I hav..."
2050,diabetes,I regularly experience these intense urges and...
2051,diabetes,"I have trouble breathing, especially outside. ..."
2052,diabetes,I constantly sneeze and have a dry cough. My i...

In [88]:
df['label'].unique()

<ArrowStringArray>
[           'cervical spondylosis',                        'impetigo',
         'urinary tract infection',                       'arthritis',
                          'dengue',                     'common cold',
                   'drug reaction',                'fungal infection',
                         'malaria',                         'allergy',
                'bronchial asthma',                  'varicose veins',
                        'migraine',                    'hypertension',
 'gastroesophageal reflux disease',                       'pneumonia',
                       'psoriasis',                        'diabetes',
                        'jaundice',                     'chicken pox',
                         'typhoid',            'peptic ulcer disease',
           'dimorphic hemorrhoids',                            'acne']
Length: 24, dtype: str

In [89]:
df['label'].value_counts()

label
cervical spondylosis               90
impetigo                           90
arthritis                          90
dengue                             90
drug reaction                      90
malaria                            90
allergy                            90
bronchial asthma                   90
varicose veins                     90
hypertension                       90
psoriasis                          90
diabetes                           90
chicken pox                        90
urinary tract infection            89
common cold                        89
fungal infection                   89
gastroesophageal reflux disease    89
typhoid                            88
pneumonia                          87
peptic ulcer disease               87
jaundice                           83
migraine                           82
dimorphic hemorrhoids              50
acne                               50
Name: count, dtype: int64

In [90]:
df.duplicated().sum()
df = df.drop_duplicates()

In [91]:
df.duplicated().sum()

np.int64(0)

In [93]:
df['label'].value_counts()

label
impetigo                           90
psoriasis                          90
diabetes                           90
urinary tract infection            89
drug reaction                      89
allergy                            89
varicose veins                     89
hypertension                       89
chicken pox                        89
common cold                        88
bronchial asthma                   88
typhoid                            88
cervical spondylosis               87
dengue                             87
fungal infection                   87
gastroesophageal reflux disease    86
peptic ulcer disease               86
arthritis                          84
malaria                            84
pneumonia                          84
migraine                           79
jaundice                           69
acne                               46
dimorphic hemorrhoids              41
Name: count, dtype: int64

In [94]:
df.to_csv("data.csv", index=False)